-- vim.g.neovide_fullscreen = true
vim.g.neovide_remember_window_size = true
vim.g.neovide_cursor_vfx_mode = "railgun"
vim.g.neovide_cursor_vfx_particle_density = 14.0
vim.g.neovide_cursor_vfx_particle_phase = 15.0
vim.g.neovide_cursor_vfx_particle_curl = 0.0
-- vim.opt.guifont = { "RobotoMono Nerd Font", ":h14" }
-- vim.opt.guifont = { "Lilex Nerd Font", ":h14" }
vim.g.neovide_input_macos_option_key_is_meta = "both"
vim.g.neovide_floating_blur_amount_x = 10.0
vim.g.neovide_floating_blur_amount_y = 10.0
